name: DANTES - Defense Activity for Non-Traditional Education Support
base_url: http://www.dantes.doded.mil
fb_app_id: 586726141400126
markdown: redcarpet
pygments: false
destination: ../source
searchindex: yes
indextank_index: DANTES
indextank_api_url: http://:bazadesumygy@teqaze.api.indexden.com
lunr_search:
  excludes: [rss.xml, atom.xml]
  min_length: 3
include: ['robots.txt', '_js', '_images', '_css', '_content']
